import { jsPDF } from 'jspdf';
import { StateData } from '../store/useSessionStore';

export async function generatePDFReport(state: StateData, problemText: string) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let cursorY = margin;

  const addText = (text: string, fontSize: number, isBold: boolean, color: number[]) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    
    // Check page break
    if (cursorY + (lines.length * fontSize * 0.4) > pageHeight - margin) {
      doc.addPage();
      cursorY = margin;
    }
    
    doc.text(lines, margin, cursorY);
    cursorY += (lines.length * fontSize * 0.4) + 5;
  };

  const addSectionTitle = (title: string) => {
    cursorY += 5;
    addText(title, 16, true, [99, 102, 241]); // titan-blue
    doc.setLineWidth(0.5);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, cursorY - 3, pageWidth - margin, cursorY - 3);
    cursorY += 5;
  };

  // Header
  addText('TITAN GOVERNANCE INTELLIGENCE', 24, true, [10, 10, 10]);
  addText('Official Executive Report', 12, false, [100, 100, 100]);
  cursorY += 10;

  // 1. Problem
  addSectionTitle('Core Problem Statement');
  addText(problemText || 'N/A', 11, false, [40, 40, 40]);

  // 2. Debate Summary
  addSectionTitle('Debate Summary');
  if (state.debates.length > 0) {
    const debateText = state.debates.map(d => 
      `[${d.agent_role.toUpperCase()} - ${d.phase.toUpperCase()}]\n${d.argument}`
    ).join('\n\n');
    addText(debateText, 10, false, [60, 60, 60]);
  } else {
    addText('No debate records found.', 10, false, [60, 60, 60]);
  }

  // 3. Votes
  addSectionTitle('Cabinet Votes');
  if (state.votes.length > 0) {
    state.votes.forEach(v => {
      addText(`${v.agent_role.toUpperCase()} (${Math.round(v.confidence_score)}% Confidence)`, 11, true, [10, 10, 10]);
      addText(`Voted for: ${v.voted_option}`, 10, false, [40, 40, 40]);
      addText(`Justification: ${v.justification}`, 10, false, [60, 60, 60]);
      cursorY += 2;
    });
  }

  // 4. Simulation Results
  addSectionTitle('Simulation Stress Tests');
  if (state.simulations.length > 0) {
    state.simulations.forEach(s => {
      addText(`Scenario: ${s.option_description} (${s.risk_level.toUpperCase()} RISK)`, 11, true, [10, 10, 10]);
      addText(`Scores - Econ: ${Math.round(s.economic_score)} | Env: ${Math.round(s.environmental_score)} | Social: ${Math.round(s.social_score)} | Feasibility: ${Math.round(s.feasibility_score)}`, 10, false, [40, 40, 40]);
      addText(`Key Risk: ${s.key_risks?.[0] || 'N/A'}`, 10, false, [60, 60, 60]);
      cursorY += 2;
    });
  }

  // 5. Final Strategy
  addSectionTitle('Final Binding Strategy');
  if (state.finalReport) {
    addText(state.finalReport.chosen_option, 14, true, [10, 10, 10]);
    cursorY += 2;
    addText(`Confidence Score: ${Math.round(state.finalReport.confidence_score || 85)}/100`, 11, true, [16, 185, 129]); // green
    cursorY += 3;
    
    addText('Executive Summary:', 11, true, [10, 10, 10]);
    addText(state.finalReport.executive_summary, 10, false, [40, 40, 40]);
    
    addText('Strategic Rationale:', 11, true, [10, 10, 10]);
    addText(state.finalReport.overall_rationale || state.finalReport.rationale || '', 10, false, [40, 40, 40]);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by TITAN Autonomous Engine - ${new Date().toISOString()}`, margin, pageHeight - 10);

  doc.save(`TITAN_Report_${state.projectId?.split('-')[0] || 'Unknown'}.pdf`);
}
